[package]
name = "gl-wrapper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
thiserror = "1.0"
image = "*"
nalgebra-glm="0.18.0"